### PR TITLE
Update Workspaces Client to 2024.4

### PR DESCRIPTION
**Pull request by claer**
Update Workspaces Client to 2024.4. Works for me :)

Update .spec 'Conflicts' copy/paste bug.

### CODE REVIEW

**Comment by BOPOHA** [comment]
@claer :) thanks
the question is about deleting `rpmlint.result` file. How do you do the update?

**Comment by BOPOHA** [comment]
actually i want to ask you to install the `rpmlint` and run `make all` again

**Comment by claer** [comment]
I didn't pay attention rpmlint is not in base rpm tools.  Do you want me to squash the commits?

**Comment by BOPOHA** [comment]
nope, i will

**Pull request merged**
